import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNavigationMenu from "@/public/class/HeaderNavigationMenu";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

const navMenu = [
  new HeaderNavigationMenu({
    title: "통장",
    path: "/product-service/account",
    navId: "acc1",
  }),
  new HeaderNavigationMenu({
    title: "예금·적금",
    path: "/product-service/savings",
    navId: "de-sa",
  }),
  new HeaderNavigationMenu({
    title: "대출",
    path: "/product-service/loan",
    navId: "loan",
  }),
  new HeaderNavigationMenu({
    title: "외환",
    path: "/product-service/foreign-exchange",
    navId: "foreign-exchange",
  }),
  new HeaderNavigationMenu({
    title: "카드",
    path: "/product-service/card",
    navId: "card",
  }),
  new HeaderNavigationMenu({
    title: "은행소개",
    path: "/about/introduce",
    navId: "introduce",
  }),
  new HeaderNavigationMenu({
    title: "고객센터",
    path: "/customer",
    navId: "service",
  }),
  new HeaderNavigationMenu({ title: "채용", path: "/recruit", navId: "rec" }),
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header className="w-full h-16 bg-black opacity-85">
          <nav className="h-full flex justify-center items-center">
            <Link href={"/"} className="mr-5">
              <Image
                src={"svg/logo-bank-mono-light.svg"}
                alt={"헤더 로고"}
                width={118}
                height={20}
              />
            </Link>
            <ul className="flex text-sub">
              {navMenu.map((menu) => (
                <li key={menu.navId} className="mr-5">
                  <Link href={menu.path}>{menu.title}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
